### ISSUE TITLE
Rearrange bottom-of-page buttons.

### ISSUE THREAD

**Issue by portalhugger** [azamo1011/BASALT#12]
We'd like to try formatting the bottom-of-page buttons to resemble Github's bottom-of-page links. Centered, justified, and separated in the middle by either the SCP or Basalt logo.

**Comment by SYwaves** [comment]
Unclear what this entails specifically. More information or mockup is required.

**Comment by LirynSCP** [comment]
Desirable result achieved through Bedrock.
