### ISSUE TITLE
Add a period after the end of the licensing notice at the bottom of the page.

### ISSUE THREAD

**Issue by Yossipossi1** [azamo1011/BASALT#13]
This has been a serious issue for a long time which Sigma-9 has failed to address. The sentence at the bottom of each page exclaiming the site's licensing lacks a period. This is an egregious oversight by the developers of Wikidot, and thus requires manual fixing. [Black Highlighter](https://github.com/Nu-SCPTheme/Black-Highlighter) has already fixed this, and thus we should as well.

Here you can see the current appearance of the licensing notice (note the lack of period):

![image](https://user-images.githubusercontent.com/86030912/141379524-a7b5009d-ce76-45a4-9d35-716e03c430f3.png)

Here are my proposed changes to the theme implemented on a local build (i.e. inspect element):

![image](https://user-images.githubusercontent.com/86030912/141379988-71ac7f42-89d6-4c69-b419-05db3983e0e9.png)

This can be achieved with the following code:

```
#license-area a::after {
    content: '.'
}
```

I urge the developers of BASALT to immediately fix this issue without delay. It is of utmost importance.

**Comment by SYwaves** [comment]
Solved.
