### ISSUE TITLE
Logo Quality Change

### ISSUE THREAD

**Issue by JackIke** [azamo1011/BASALT#17]
When the page first loads, the logo in the top-left corner is duller and slightly blurry; when the logo is hovered over and the tilt animation plays, the logo visibly brightens and becomes crisper, and stays that way until the page is reloaded.

Just a request to tweak it somehow so that no change in brightness / crispness occurs (with preference for the crisper appearance from the outset)

**Comment by SYwaves** [comment]
This has been partly mitigated by switching to SVG, but this is a browser rasterization issue before Basalt's.
