### ISSUE TITLE
Multiple fonts for localization are not imported 

### ISSUE THREAD

**Issue by hoah2333** [azamo1011/BASALT#22]
Multiple fonts for localization are not imported, including [Noto Sans SC](https://fonts.google.com/noto/specimen/Noto+Sans+SC), [Noto Serif SC](https://fonts.google.com/noto/specimen/Noto+Serif+SC), [Noto Sans TC](https://fonts.google.com/noto/specimen/Noto+Sans+TC), [Kanit](https://fonts.google.com/specimen/Kanit), Charcoal (not sure if it exists on Google Fonts), [Nanum Gothic](https://fonts.google.com/specimen/Nanum+Gothic) and so on.

**Comment by SYwaves** [comment]
done except for fonts that are not web-available or difficult to implement
