### ISSUE TITLE
Mobile mod not working.

### ISSUE THREAD

**Issue by loprima-l** [azamo1011/BASALT#30]
I'm currently working on this wikidot : http://scp-tsade.wikidot.com/

And the mobile version looks the same as the desktop one.
Do you know what can cause that ?

We're importing basalt from a main css file inspired from the one used on the basalt page, maybe we're doing it wrong, it would be nice to get a documentation on that !

**Comment by SYwaves** [comment]
This is likely because your site does not have the meta tag ` <meta name="viewport" content="width=device-width, initial-scale=1.0"/>`, and has nothing to do with the CSS.

You can add it under `+ Options` > `Edit Meta` on Wikidot.

**Comment by loprima-l** [comment]
Thank u very much it worked !
