### ISSUE TITLE
Add alternative top-bar formats.

### ISSUE THREAD

**Issue by portalhugger** [azamo1011/BASALT#6]
Include variable allowing a centered header format and potential others. (removal of topbar entirely?)

Concept art for this or possible other alternatives: 
![](https://cdn.discordapp.com/attachments/750369579456528505/866021055466045500/topbar.png)
 
![image](https://user-images.githubusercontent.com/16965491/141358315-4bed600a-1019-4865-88c0-c6309612fb48.png)

**Comment by SYwaves** [comment]
Mockup depicted is impossible or extremely finnicky without DOM control. Will not implement for now.
