### ISSUE TITLE
Increase accessibility of color customization.

### ISSUE THREAD

**Issue by portalhugger** [azamo1011/BASALT#8]
Like BHL: The colors of all the elements on the page are governed by a bunch of root variables that can be easily overwritten by the user. Additionally, present a few different preset palettes like Monotypical. 

(I wonder if darkmode should be presented as one of these presets, or if it requires so many other elements to change that it needs to remain an include variable).

**Comment by LirynSCP** [comment]
Achieved with Bedrock.
